[libraries]
lib.files = [
  "clock.vhd",
  "clock_tb.vhd",
]
IP.files = [
  "../IP/T18_Timer.vhd",
  "../IP/clock_divider.vhd",
  "../IP/counter.vhd",
  "../IP/d_flip_flop.vhd",
  "../IP/d_latch.vhd",
  "../IP/debouncer.vhd",
  "../IP/full_adder.vhd",
  "../IP/half_adder.vhd",
  "../IP/pad_mod_behav.vhd",
  "../IP/pwm.vhd",
]
